DevHelper.CS-main/DevHelper/Pages/PgArquivoProblema/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DevHelper.Data.Model;

namespace DevHelper.Razor.Pages.PgArquivoProblema
{
    public class CreateModel : PageModel
    {
        private readonly DevHelper.Data.Model.DBdevhelperContext _context;

        public CreateModel(DevHelper.Data.Model.DBdevhelperContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["ProblemaId"] = new SelectList(_context.Problemas, "Id", "Descricao");
            return Page();
        }

        [BindProperty]
        public ArquivoProblema ArquivoProblema { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.ArquivoProblemas.Add(ArquivoProblema);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

DevHelper.CS-main/DevHelper/Pages/PgArquivoProblema/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DevHelper.Data.Model;

namespace DevHelper.Razor.Pages.PgArquivoProblema
{
    public class DeleteModel : PageModel
    {
        private readonly DevHelper.Data.Model.DBdevhelperContext _context;

        public DeleteModel(DevHelper.Data.Model.DBdevhelperContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ArquivoProblema ArquivoProblema { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivoproblema = await _context.ArquivoProblemas.FirstOrDefaultAsync(m => m.Id == id);

            if (arquivoproblema == null)
            {
                return NotFound();
            }
            else
            {
                ArquivoProblema = arquivoproblema;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivoproblema = await _context.ArquivoProblemas.FindAsync(id);
            if (arquivoproblema != null)
            {
                ArquivoProblema = arquivoproblema;
                _context.ArquivoProblemas.Remove(ArquivoProblema);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

DevHelper.CS-main/DevHelper/Pages/PgArquivoProblema/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DevHelper.Data.Model;

namespace DevHelper.Razor.Pages.PgArquivoProblema
{
    public class DetailsModel : PageModel
    {
        private readonly DevHelper.Data.Model.DBdevhelperContext _context;

        public DetailsModel(DevHelper.Data.Model.DBdevhelperContext context)
        {
            _context = context;
        }

        public ArquivoProblema ArquivoProblema { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivoproblema = await _context.ArquivoProblemas.FirstOrDefaultAsync(m => m.Id == id);
            if (arquivoproblema == null)
            {
                return NotFound();
            }
            else
            {
                ArquivoProblema = arquivoproblema;
            }
            return Page();
        }
    }
}

DevHelper.CS-main/DevHelper/Pages/PgArquivoProblema/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DevHelper.Data.Model;

namespace DevHelper.Razor.Pages.PgArquivoProblema
{
    public class EditModel : PageModel
    {
        private readonly DevHelper.Data.Model.DBdevhelperContext _context;

        public EditModel(DevHelper.Data.Model.DBdevhelperContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ArquivoProblema ArquivoProblema { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivoproblema =  await _context.ArquivoProblemas.FirstOrDefaultAsync(m => m.Id == id);
            if (arquivoproblema == null)
            {
                return NotFound();
            }
            ArquivoProblema = arquivoproblema;
           ViewData["ProblemaId"] = new SelectList(_context.Problemas, "Id", "Descricao");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ArquivoProblema).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ArquivoProblemaExists(ArquivoProblema.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ArquivoProblemaExists(int id)
        {
            return _context.ArquivoProblemas.Any(e => e.Id == id);
        }
    }
}

DevHelper.CS-main/DevHelper/Pages/PgArquivoSolucao/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DevHelper.Data.Model;

namespace DevHelper.Razor.Pages.PgArquivoSolucao
{
    public class CreateModel : PageModel
    {
        private readonly DevHelper.Data.Model.DBdevhelperContext _context;

        public CreateModel(DevHelper.Data.Model.DBdevhelperContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["SolucaoId"] = new SelectList(_context.Solucoes, "Id", "Descricao");
            return Page();
        }

        [BindProperty]
        public ArquivoSolucao ArquivoSolucao { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.ArquivoSolucoes.Add(ArquivoSolucao);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

DevHelper.CS-main/DevHelper/Pages/PgArquivoSolucao/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DevHelper.Data.Model;

namespace DevHelper.Razor.Pages.PgArquivoSolucao
{
    public class DeleteModel : PageModel
    {
        private readonly DevHelper.Data.Model.DBdevhelperContext _context;

        public DeleteModel(DevHelper.Data.Model.DBdevhelperContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ArquivoSolucao ArquivoSolucao { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivosolucao = await _context.ArquivoSolucoes.FirstOrDefaultAsync(m => m.Id == id);

            if (arquivosolucao == null)
            {
                return NotFound();
            }
            else
            {
                ArquivoSolucao = arquivosolucao;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivosolucao = await _context.ArquivoSolucoes.FindAsync(id);
            if (arquivosolucao != null)
            {
                ArquivoSolucao = arquivosolucao;
                _context.ArquivoSolucoes.Remove(ArquivoSolucao);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

DevHelper.CS-main/DevHelper/Pages/PgArquivoSolucao/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DevHelper.Data.Model;

namespace DevHelper.Razor.Pages.PgArquivoSolucao
{
    public class DetailsModel : PageModel
    {
        private readonly DevHelper.Data.Model.DBdevhelperContext _context;

        public DetailsModel(DevHelper.Data.Model.DBdevhelperContext context)
        {
            _context = context;
        }

        public ArquivoSolucao ArquivoSolucao { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivosolucao = await _context.ArquivoSolucoes.FirstOrDefaultAsync(m => m.Id == id);
            if (arquivosolucao == null)
            {
                return NotFound();
            }
            else
            {
                ArquivoSolucao = arquivosolucao;
            }
            return Page();
        }
    }
}

DevHelper.CS-main/DevHelper/Pages/PgArquivoSolucao/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DevHelper.Data.Model;

namespace DevHelper.Razor.Pages.PgArquivoSolucao
{
    public class EditModel : PageModel
    {
        private readonly DevHelper.Data.Model.DBdevhelperContext _context;

        public EditModel(DevHelper.Data.Model.DBdevhelperContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ArquivoSolucao ArquivoSolucao { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arquivosolucao =  await _context.ArquivoSolucoes.FirstOrDefaultAsync(m => m.Id == id);
            if (arquivosolucao == null)
            {
                return NotFound();
            }
            ArquivoSolucao = arquivosolucao;
           ViewData["SolucaoId"] = new SelectList(_context.Solucoes, "Id", "Descricao");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ArquivoSolucao).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ArquivoSolucaoExists(ArquivoSolucao.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ArquivoSolucaoExists(int id)
        {
            return _context.ArquivoSolucoes.Any(e => e.Id == id);
        }
    }
}

DevHelper.CS-main/DevHelper/Pages/PgCadUsuario/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using DevHelper.Data.Model;
using System.Security.Claims;
using DevHelper.Data.Interface;
using DevHelper.Data.Repository;
using DevHelper.Data.Interfaces;

namespace DevHelper.Razor.Pages.PgCadUsuario
{
    public class DetailsModel : PageModel
    {
        private readonly iUsuarioRepositoryAsync UsuarioRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly iProblemaRepositoryAsync ProblemaRepository;
        private readonly iSolucaoRepositoryAsync SolucaoRepository;

        public DetailsModel(iUsuarioRepositoryAsync usuariorepositoryasync, IHttpContextAccessor httpContextAccessor, iSolucaoRepositoryAsync solucaoRepository, iProblemaRepositoryAsync problemarepository)
        {
            UsuarioRepository = usuariorepositoryasync;
            _httpContextAccessor = httpContextAccessor;
            SolucaoRepository = solucaoRepository;
            ProblemaRepository = problemarepository;
        }

        [BindProperty]
        public Usuario Usuario { get; set; } = default!;

        public bool IsCurrentUser { get; set; }
        public ICollection<Problema> Problemas { get; set; } = default!;
        public ICollection<Solucao> Solucoes { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await UsuarioRepository.ObterUsuarioComProblemasESolucoesAsync(id.Value);
            if (usuario == null)
            {
                return NotFound();
            }

            Usuario = usuario;
            Problemas = usuario.Problemas ?? new List<Problema>();
            Solucoes = usuario.Solucaos ?? new List<Solucao>();

            foreach (var solucao in Solucoes)
            {
                solucao.Problema = await ProblemaRepository.SelecionaPelaChaveAsync(solucao.ProblemaId);
            }

            var loggedInUserId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            IsCurrentUser = loggedInUserId == Usuario.Id.ToString();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (Usuario == null)
            {
                return NotFound();
            }

            var loggedInUserId = int.Parse(_httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier));
            // Buscar o usuário no banco de dados com os valores antigos
            var usuarioToUpdate = await UsuarioRepository.SelecionaPelaChaveAsync(loggedInUserId);

            if (usuarioToUpdate == null)
            {
                return NotFound();
            }

            // Atualizar a biografia com o novo valor vindo do front-end
            usuarioToUpdate.Biografia = Usuario.Biografia;

            // Salvar as alterações no banco de dados
            await UsuarioRepository.AlterarAsync(usuarioToUpdate);



            //return RedirectToPage("/PgCadUsuario/Details", new { id = loggedInUserId });

            return RedirectToPage("../Index");
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("../Index");
        }
    }
}

DevHelper.CS-main/DevHelper/Pages/PgCadUsuario/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DevHelper.Data.Model;
using DevHelper.Data.Interface;

namespace DevHelper.Razor.Pages.PgCadUsuario
{
    public class IndexModel : PageModel
    {
        private readonly iUsuarioRepositoryAsync UsuarioRepository;
        public IndexModel(iUsuarioRepositoryAsync usuariorepositoryasync)
        {
            UsuarioRepository = usuariorepositoryasync;
        }

        public IList<Usuario> Usuario { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Usuario = await UsuarioRepository.SelecionTodosAsync();
        }
    }
}

DevHelper.CS-main/DevHelper/Pages/PgCadUsuario/Create.cshtml
@page
@model DevHelper.Razor.Pages.PgCadUsuario.CreateModel

@{
    ViewData["Title"] = "Cadastro";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header">
                    <h1>Cadastro do Usuário</h1>
                </div>
                <div class="card-body">
                    <form method="post">
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>

                        <div class="form-group">
                            <label asp-for="Usuario.Nome" class="control-label"></label>
                            <input asp-for="Usuario.Nome" class="form-control" />
                            <span asp-validation-for="Usuario.Nome" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Usuario.Email" class="control-label"></label>
                            <input asp-for="Usuario.Email" class="form-control" />
                            <span asp-validation-for="Usuario.Email" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-4">
                            <label asp-for="Usuario.Senha" class="control-label"></label>
                            <input asp-for="Usuario.Senha" class="form-control" type="password" />
                            <span asp-validation-for="Usuario.Senha" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-4">
                            <label asp-for="Usuario.Biografia" class="control-label"></label>
                            <textarea asp-for="Usuario.Biografia" class="form-control" rows="5" maxlength="1500"></textarea>
                            <span asp-validation-for="Usuario.Biografia" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-4">
                            <input type="submit" value="Cadastrar" class="btn btn-custom" />
                        </div>
                        <a asp-page="/Index" class="text-black">Voltar ao Login</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<style>
    .btn.btn-custom {
        background-color: #22ffb6;
        color: #000;
        border: none;
        text-align: center;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 100%;
    }

        .btn.btn-custom:hover {
            background-color: #1ccc9a;
            color: #fff;
        }

    .text-black {
        color: #000;
    }

        .text-black:hover {
            color: #22ffb6;
        }
</style>

DevHelper.CS-main/DevHelper/Pages/PgCadUsuario/Delete.cshtml
@page
@model DevHelper.Razor.Pages.PgCadUsuario.DeleteModel

@{
    ViewData["Title"] = "Excluir";
}


<h1>Deseja realmente excluir sua conta?</h1>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario.Biografia)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Biografia)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Usuario.Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> 
    </form>
</div>

DevHelper.CS-main/DevHelper/Pages/PgCadUsuario/Details.cshtml
@page
@model DevHelper.Razor.Pages.PgCadUsuario.DetailsModel
@using System.Security.Claims
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    var user = HttpContextAccessor.HttpContext.User;
    var userId = user.FindFirstValue(ClaimTypes.NameIdentifier);
    var userName = user.FindFirstValue(ClaimTypes.Name);
    var isOwner = Model.Usuario != null && userId == Model.Usuario.Id.ToString();
}

<h1 class="d-flex justify-content-between align-items-center">
    @Html.DisplayFor(model => model.Usuario.Nome)
    @if (isOwner)
    {
        <div class="d-flex">
            <div class="flex-fill me-2">
                <form method="post" asp-page-handler="Logout" class="m-0 p-0 h-100">
                    <button type="submit" class="btn btn-custom w-100 h-100 d-flex align-items-center justify-content-center">Logout</button>
                </form>
            </div>
            <div class="flex-fill">
                <a asp-page="/PgCadUsuario/Delete" asp-route-id="@userId" class="btn btn-custom w-100 h-100 d-flex align-items-center justify-content-center">Delete Account</a>
            </div>
        </div>
    }
</h1>

<div>
    <hr />
    <form method="post" style="margin-bottom: 20px;">
        <dl class="row">
            <dt class="col-sm-12">
                @Html.DisplayNameFor(model => model.Usuario.Biografia)
            </dt>
            <dd class="col-sm-12">
                @if (isOwner)
                {
                    <textarea asp-for="Usuario.Biografia" class="form-control w-100" rows="5"></textarea>
                }
                else
                {
                    <textarea asp-for="Usuario.Biografia" class="form-control w-100" rows="5" readonly></textarea>
                }
            </dd>
        </dl>

        @if (isOwner)
        {
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-custom">Salvar Alterações</button>
            </div>
        }
    </form>
</div>

<div class="row">
    <div class="col-md-6 border-end">
        <h3>Problemas</h3>
        @if (Model.Problemas != null && Model.Problemas.Any())
        {
            <table class="table table-light fixed-table">
                <thead>
                    <tr>
                        <th style="width: 30%;">Nome</th>
                        <th style="width: 55%;">Descrição</th>
                        <th style="width: 15%;"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var problema in Model.Problemas)
                    {
                        <tr>
                            <td>@problema.Nome</td>
                            <td>@TruncateText(problema.Descricao, 150)</td>
                            <td>
                                <a asp-page="/PgProblema/Details" asp-route-id="@problema.Id" class="btn btn-sm btn-custom">Detalhes</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Nenhum problema encontrado.</p>
        }
    </div>
    <div class="col-md-6">
        <h3>Soluções</h3>
        @if (Model.Solucoes != null && Model.Solucoes.Any())
        {
            <table class="table table-light fixed-table">
                <thead>
                    <tr>
                        <th style="width: 30%;">Nome</th>
                        <th style="width: 55%;">Descrição</th>
                        <th style="width: 15%;"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var solucao in Model.Solucoes)
                    {
                        <tr>
                            <td>@solucao.Problema?.Nome</td>
                            <td>@TruncateText(solucao.Descricao, 150)</td>
                            <td>
                                <a asp-page="/PgSolucao/Details" asp-route-id="@solucao.Id" class="btn btn-sm btn-custom">Detalhes</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Nenhuma solução encontrada.</p>
        }
    </div>
</div>

@functions {
    string TruncateText(string text, int maxLength)
    {
        if (string.IsNullOrEmpty(text) || text.Length <= maxLength)
        {
            return text;
        }

        // Tentativa de truncar sem quebrar palavras
        int end = maxLength;
        while (end > 0 && text[end] != ' ')
        {
            end--;
        }

        // Se não houver espaço, simplesmente truncar no limite máximo de caracteres
        if (end == 0)
        {
            end = maxLength;
        }

        return text.Substring(0, end) + "...";
    }
}

<style>
    .btn.btn-custom {
        background-color: #22ffb6;
        color: #000;
        border: none;
        text-align: center;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 100%;
    }

        .btn.btn-custom:hover {
            background-color: #1ccc9a;
            color: #fff;
        }

    .text-custom {
        color: #22ffb6;
    }

    .table-light {
        background-color: #f9f9f9;
        color: #000;
    }

    .fixed-table th, .fixed-table td {
        border: 1px solid #333;
        word-wrap: break-word;
        white-space: pre-line;
    }

    .list-group-item {
        border: none;
        border-bottom: 1px solid #555;
    }

        .list-group-item:last-child {
            border-bottom: none;
        }

    .float-end {
        float: right;
    }

    /* Ajustes para garantir a flexibilidade das tabelas */
    .table {
        table-layout: fixed;
        width: 100%;
    }
</style>

DevHelper.CS-main/DevHelper/Pages/PgCadUsuario/Edit.cshtml
@page
@model DevHelper.Razor.Pages.PgCadUsuario.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Usuario.Id" />
            <div class="form-group">
                <label asp-for="Usuario.Nome" class="control-label"></label>
                <input asp-for="Usuario.Nome" class="form-control" />
                <span asp-validation-for="Usuario.Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usuario.Email" class="control-label"></label>
                <input asp-for="Usuario.Email" class="form-control" />
                <span asp-validation-for="Usuario.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usuario.Senha" class="control-label"></label>
                <input asp-for="Usuario.Senha" class="form-control" />
                <span asp-validation-for="Usuario.Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usuario.Biografia" class="control-label"></label>
                <input asp-for="Usuario.Biografia" class="form-control" />
                <span asp-validation-for="Usuario.Biografia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}